HOME: home
CONTENTDIR: home
OUTPUTDIR: output
REPORTSDIR: bones/reports
GENERATEDCONTENTDIR: home/generated
baseurl: "https://yoursite.com"
defaulttemplate: "rot-doc.html"
generateindexes: true
SCENARIO: default