

#!/usr/bin/env python3
"""
Self-contained Rotkeeper project initializer.
Run this script to scaffold a new Rotkeeper project.
"""

from pathlib import Path
import argparse

def init_project(base_path: Path, force: bool = False):
    print(f"Initializing Rotkeeper project in: {base_path}")

    # Directories to create
    directories = [
        base_path / "content",
        base_path / "bones" / "templates",
        base_path / "bones" / "config",
        base_path / "bones" / "reports",
    ]

    for directory in directories:
        if directory.exists() and not force:
            print(f"  - Skipping existing directory: {directory.relative_to(base_path)}")
        else:
            directory.mkdir(parents=True, exist_ok=True)
            print(f"  ✓ Created {directory.relative_to(base_path)}/")

    # Sample Markdown
    sample_md = base_path / "content" / "sample.md"
    if not sample_md.exists() or force:
        sample_md.write_text("""---
title: Sample Document
author: Your Name
date: 2026-03-14
tags: [sample, getting-started]
---

# Welcome to Rotkeeper

This is a sample Markdown document to get you started.
""")
        print(f"  ✓ Created {sample_md.relative_to(base_path)}")
    else:
        print(f"  - Skipping existing file: {sample_md.relative_to(base_path)}")

    # Default HTML template (plainstone)
    default_template = base_path / "bones" / "templates" / "default.html"
    if not default_template.exists() or force:
        default_template.write_text("""<!DOCTYPE html>
<html>
  <head>
    <title>$title$</title>
  </head>
  <body>
    $body$
  </body>
</html>
""")
        print(f"  ✓ Created {default_template.relative_to(base_path)}")
    else:
        print(f"  - Skipping existing file: {default_template.relative_to(base_path)}")

    # render-flags.yaml
    render_flags = base_path / "bones" / "config" / "render-flags.yaml"
    if not render_flags.exists() or force:
        render_flags.write_text("""# Rotkeeper Render Configuration
default_template: default
output_dir: output
markdown_extensions:
  - tables
  - fenced_code
  - codehilite
  - toc
  - attr_list
  - def_list
render_options:
  generate_toc: true
  code_theme: default
  output_extension: .html
  pretty_html: true
manifest:
  enabled: true
  filename: manifest.json
  include_hashes: true
watch:
  watch_dirs:
    - content
    - bones/templates
    - bones/config
  patterns:
    - "*.md"
    - "*.html"
    - "*.yaml"
  debounce_ms: 500
""")
        print(f"  ✓ Created {render_flags.relative_to(base_path)}")
    else:
        print(f"  - Skipping existing file: {render_flags.relative_to(base_path)}")

    # Reports README
    reports_readme = base_path / "bones" / "reports" / "README.md"
    if not reports_readme.exists() or force:
        reports_readme.write_text("# Render Reports\n\nThis folder contains manifests and logs generated by Rotkeeper.")
        print(f"  ✓ Created {reports_readme.relative_to(base_path)}")
    else:
        print(f"  - Skipping existing file: {reports_readme.relative_to(base_path)}")

    # .gitignore
    gitignore = base_path / ".gitignore"
    if not gitignore.exists() or force:
        gitignore.write_text("""output/
*.html
!bones/templates/*.html
__pycache__/
*.py[cod]
.venv/
env/
*.swp
.DS_Store
""")
        print(f"  ✓ Created {gitignore.relative_to(base_path)}")
    else:
        print(f"  - Skipping existing file: {gitignore.relative_to(base_path)}")

    print("\n✨ Rotkeeper project initialized successfully!")
    print("Next steps:")
    print("  1. Edit content/sample.md or add new Markdown files")
    print("  2. Customize bones/templates/default.html")
    print("  3. Run your rendering pipeline to generate output")
    print("  4. Check bones/reports/ for rendering manifests\n")

def main():
    parser = argparse.ArgumentParser(description="Initialize a new Rotkeeper project")
    parser.add_argument("--force", action="store_true", help="Overwrite existing files")
    parser.add_argument("--path", type=str, default=".", help="Project directory (default: current folder)")
    args = parser.parse_args()

    base_path = Path(args.path).resolve()
    init_project(base_path, force=args.force)

if __name__ == "__main__":
    main()