from __future__ import annotations

import argparse
import shutil

from pathlib import Path
from ..context import RunContext
from ..config import CONFIG


def add_parser(subs: argparse._SubParsersAction) -> None:
    p = subs.add_parser("init", help="Initialize environment")
    p.add_argument("--force", action="store_true", help="Force rebuild/re-init")
    p.set_defaults(func=run)


def run(args: argparse.Namespace, ctx: RunContext | None = None) -> int:
    base_dir = Path.cwd()
    home = CONFIG.HOME
    bones = CONFIG.BONES
    force = bool(getattr(args, "force", False))

    print(f"Initializing rotkeeper project in: {base_dir}")

    # Directories to create under home and bones
    directories = [
        CONFIG.CONTENT_DIR,
        bones / "templates",
        bones / "assets" / "styles",
        bones / "assets" / "images",
        bones / "config",
        bones / "reports",
    ]

    for directory in directories:
        if directory.exists() and not force:
            print(f" - Skipping existing directory: {directory.relative_to(base_dir)}")
        else:
            directory.mkdir(parents=True, exist_ok=True)
            print(f" ✓ Created {directory.relative_to(base_dir)}/")

    # Write user preferences to user-config.yaml
    user_config = bones / "config" / "user-config.yaml"
    if not user_config.exists() or force:
        user_config.write_text(
            "HOME: home\n"
            "CONTENT_DIR: home/content\n"
            "OUTPUT_DIR: home/output\n"
            "default_template: default\n"
        )
        print(f" ✓ Created {user_config.relative_to(base_dir)}")
    else:
        print(f" - Skipping existing file: {user_config.relative_to(base_dir)}")

    # Define SOURCES_DIR for source files
    SOURCES_DIR = Path(__file__).parent.parent / "sources"

    # Copy content files
    content_files = ["index.md", "sample.md"]
    for filename in content_files:
        src = SOURCES_DIR / "content" / filename
        dst = CONFIG.CONTENT_DIR / filename
        if not dst.exists() or force:
            shutil.copy2(src, dst)
            print(f" ✓ Created {dst.relative_to(base_dir)}")
        else:
            print(f" - Skipping existing file: {dst.relative_to(base_dir)}")

    # Copy template files
    templates_src_dir = SOURCES_DIR / "templates"
    templates_dst_dir = bones / "templates"
    if templates_src_dir.exists():
        for template_file in templates_src_dir.iterdir():
            if template_file.is_file():
                dst_file = templates_dst_dir / template_file.name
                if not dst_file.exists() or force:
                    shutil.copy2(template_file, dst_file)
                    print(f" ✓ Created {dst_file.relative_to(base_dir)}")
                else:
                    print(f" - Skipping existing file: {dst_file.relative_to(base_dir)}")

    # Copy SCSS style files
    styles_src_dir = SOURCES_DIR / "styles"
    styles_dst_dir = bones / "assets" / "styles"
    if styles_src_dir.exists():
        for style_file in styles_src_dir.iterdir():
            if style_file.is_file():
                dst_file = styles_dst_dir / style_file.name
                if not dst_file.exists() or force:
                    shutil.copy2(style_file, dst_file)
                    print(f" ✓ Created {dst_file.relative_to(base_dir)}")
                else:
                    print(f" - Skipping existing file: {dst_file.relative_to(base_dir)}")

    # Copy mascot.png image file
    mascot_src = SOURCES_DIR / "images" / "mascot.png"
    mascot_dst_dir = bones / "assets" / "images"
    mascot_dst = mascot_dst_dir / "mascot.png"
    if mascot_src.exists():
        if not mascot_dst.exists() or force:
            shutil.copy2(mascot_src, mascot_dst)
            print(f" ✓ Created {mascot_dst.relative_to(base_dir)}")
        else:
            print(f" - Skipping existing file: {mascot_dst.relative_to(base_dir)}")

    # Reports README inside bones/reports
    reports_readme = bones / "reports" / "README.md"
    if not reports_readme.exists() or force:
        reports_readme.write_text("# Render Reports\n\nThis folder contains manifests and logs generated by Rotkeeper.")
        print(f" ✓ Created {reports_readme.relative_to(base_dir)}")
    else:
        print(f" - Skipping existing file: {reports_readme.relative_to(base_dir)}")

    # .gitignore in root
    gitignore = base_dir / ".gitignore"
    if not gitignore.exists() or force:
        gitignore.write_text("""output/
*.html
!bones/templates/*.html
bones/assets/styles/*.css
__pycache__/
*.py[cod]
.venv/
env/
*.swp
.DS_Store
""")
        print(f" ✓ Created {gitignore.relative_to(base_dir)}")
    else:
        print(f" - Skipping existing file: {gitignore.relative_to(base_dir)}")

    print("\n✨ Rotkeeper project initialized successfully!")
    print("Next steps:")
    print(" 1. Edit home/content/sample.md or add new Markdown files")
    print(" 2. Customize bones/templates/default.html and bones/assets/styles/*.scss")
    print(" 3. Run 'rotkeeper render' to generate output")
    print(" 4. Check bones/reports/ for rendering manifests\n")

    return 0
